### ISSUE TITLE
Impossible to install requests

### ISSUE THREAD

**Issue by Etiennepicard** [manthey/pyexe#32]
When attempting to install requests using the py36-64 executable, pip finds all the required packages, but then gives this error:

Exception:
Traceback (most recent call last):
  File "site-packages\pip\_internal\basecommand.py", line 228, in main
  File "site-packages\pip\_internal\commands\install.py", line 335, in run
  File "site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
  File "site-packages\pip\_internal\req\req_install.py", line 748, in install
  File "site-packages\pip\_internal\req\req_install.py", line 961, in move_wheel_files
  File "site-packages\pip\_internal\wheel.py", line 461, in move_wheel_files
  File "site-packages\pip\_vendor\distlib\scripts.py", line 414, in make_multiple
  File "site-packages\pip\_vendor\distlib\scripts.py", line 403, in make
  File "site-packages\pip\_vendor\distlib\scripts.py", line 307, in _make_script
  File "site-packages\pip\_vendor\distlib\scripts.py", line 243, in _write_script
  File "site-packages\pip\_vendor\distlib\scripts.py", line 382, in _get_launcher
  File "site-packages\pip\_vendor\distlib\resources.py", line 329, in finder
pip._vendor.distlib.DistlibException: Unable to locate finder for 'pip._vendor.distlib'
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Is there any way around this?

**Comment by manthey** [comment]
@Etiennepicard I was away for the last few weeks -- I'll look into this sometime this week.
