### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode  when scripts comment has chinese

### ISSUE THREAD

**Issue by yanghuan** [manthey/pyexe#43]
Traceback (most recent call last):
  File "pyexe.py", line 1199, in <module>
  File "pyexe.py", line 1150, in main
  File "pyexe.py", line 863, in run_file
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 91: illegal multibyte sequence
[167744] Failed to execute script pyexe

**Comment by manthey** [comment]
@yanghuan Can you upload a small script that shows this behavior?

**Comment by yanghuan** [comment]
the test.py content is follow
```
#encoding=utf-8

# need, 需要

if __name__ == '__main__':
	print('hello')
```
run will report 
"Traceback (most recent call last):
  File "pyexe.py", line 1199, in <module>
  File "pyexe.py", line 1150, in main
  File "pyexe.py", line 863, in run_file
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 29: illegal multibyte sequence
[202636] Failed to execute script pyexe"

my operating system is  windows 10, the local language is Chinese
